services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - /mnt/app_data/postgres:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro

  backend:
    platform: linux/amd64
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ${AWS_ECR_REGISTRY}/calorie-tracker-backend:latest
    restart: always
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - db

  frontend:
    platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_LINK=${VITE_LINK}
    image: ${AWS_ECR_REGISTRY}/calorie-tracker-frontend:latest
    restart: always
    ports:
      - "80:5173"
    environment:
      - VITE_API_URL=${VITE_LINK}
    depends_on:
      - backend