name: Docker Build Check

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ "feature/**", "actions" ]

jobs:
  docker-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Compose services
        env:
          AWS_ECR_REGISTRY: localhost
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
          GOOGLE_API_KEY: test_key
          VITE_LINK: http://localhost:8000
        run: docker compose build